integrate FCM
deRonbrown/SampleApp pull request #2
Opened 2018-04-13 17:39 UTC by kbataran

Tested using RPV

2018-04-13 18:16 UTC, abashyam requested changes
The FCM id's should not be here.

2018-04-13 18:16 UTC, abashyam commented on platforms/android/google-services.json
> +{
We should replace Keys and other information sensitive information with YOUR-KEY-GOES-HERE

2018-04-16 08:25 UTC, Mriegel commented
Anand is right, We shouldn't be doing including those files here.  We should allow for it to be added by our customers so they can test push themselves if they wanted to. 

Also should update the .gitignore appropriately (and add this file to teampassword and not in confluence)

2018-04-16 14:51 UTC, Mriegel approved these changes
Make sure to rebase, but looks good

2018-04-16 14:56 UTC, merged